@extends('layout.app')

@section('title', 'Purchases Per Supplier Report')

@section('content')

<div class="container-xxl flex-grow-1 container-p-y">
    <div class="row mb-4">
        <div class="col-12">
            <h4 class="mb-1">Purchases Per Supplier Report</h4>
            <p class="text-muted">POS checkout transactions grouped by supplier (inferred via each item's supplier)</p>
        </div>
    </div>

    <!-- Filter Form -->
    <div class="card mb-4">
        <div class="card-body">
            <form method="GET" action="{{ route('admin.reports.purchases-per-supplier') }}" class="row g-3">
                <div class="col-md-4">
                    <label for="start_date" class="form-label">Start Date</label>
                    <input type="date" class="form-control" id="start_date" name="start_date" value="{{ $startDate }}">
                </div>
                <div class="col-md-4">
                    <label for="end_date" class="form-label">End Date</label>
                    <input type="date" class="form-control" id="end_date" name="end_date" value="{{ $endDate }}">
                </div>
                <div class="col-md-4 d-flex align-items-end gap-2">
                    <button type="submit" class="btn btn-primary flex-grow-1">Apply Filter</button>
                    <a href="{{ route('admin.reports.purchases-per-supplier') }}" class="btn btn-outline-secondary" title="Clear all filters">
                        <i class="bx bx-refresh"></i>
                    </a>
                </div>
            </form>
        </div>
    </div>

    <div class="alert alert-secondary">
        <i class="bx bx-info-circle me-2"></i>
        Measures revenue generated by each supplier's items sold at POS — not money paid to that supplier.
        There is no supplier-side procurement (Purchase Order / Goods Receipt) tracking in this system yet.
    </div>

    <div class="card">
        <div class="card-header">
            <h5 class="card-title mb-0">By Supplier</h5>
        </div>
        <div class="card-body">
            @forelse ($suppliers as $row)
                @if ($loop->first)
                <div class="table-responsive">
                    <table class="table table-hover">
                        <thead>
                            <tr class="table-header-bg">
                                <th>Supplier</th>
                                <th class="text-end">Transactions</th>
                                <th class="text-end">Total Amount</th>
                                <th>Last Transaction</th>
                            </tr>
                        </thead>
                        <tbody>
                @endif
                            <tr>
                                <td>{{ $row->supplier_name }}</td>
                                <td class="text-end">{{ intval($row->transactions) }}</td>
                                <td class="text-end">{{ number_format($row->total_amount, 2) }}</td>
                                <td>{{ \Illuminate\Support\Carbon::parse($row->last_purchase_at)->format('M d, Y') }}</td>
                            </tr>
                @if ($loop->last)
                        </tbody>
                    </table>
                </div>
                @endif
            @empty
                <div class="alert alert-info" role="alert">
                    <i class="bx bx-info-circle me-2"></i>
                    No purchase data for this period.
                </div>
            @endforelse
        </div>
    </div>

</div>

<style>
    .table-header-bg {
        background-color: #f7f8fa;
    }
</style>

@endsection
